### ISSUE TITLE
Pieces request! 

### ISSUE THREAD

**Issue by Zudakas** [RockerKitten/BuildIt-Castles#2]
There's "pie" pieces for flooring, they 1/8 and 1/16 floor pieces, but there isn't a curved floor without the center on the 4m flooring. Like the outside arc of the pie pieces, for example, to top the 2m to 4m curved wall transition. Also, there's not a square to circle conversion, for making a path around a tower. It leaves a weird-shaped hole in the floor.

It's really hard to see the green outline, but that piece is missing. the thing in the screenshot is actually one of the wall transitions. 
![Screenshot 2023-04-03 225312](https://user-images.githubusercontent.com/6466166/229674864-5c42b0cc-dbd0-45b1-ba4d-8e2fa83f9da7.png)

The spot inbetween the square flooring and the tower is missing a piece. 
![Screenshot 2023-04-03 225012](https://user-images.githubusercontent.com/6466166/229674324-dd1849c7-10bd-429c-b910-993068d4b30d.png)

Really love this mod, so much stuff I can build without just making box houses.

**Comment by RockerKitten** [comment]
So the transition piece from small to large was made, but apparently not added to the code for the first release. I've corrected this. I can work on a piece for square to circular though.
