### ISSUE TITLE
Non-scrolling UI in build menu

### ISSUE THREAD

**Issue by ghstwhl** [RockerKitten/BuildIt-Castles#4]
The recipe window for Structure is visibly filled in, and I believe there are a large number of other recipes available to me, but the window doesn't scroll and there are no other categories to tab between.  Is there a hot key for navigating through the available recipes?

Using version 1.0.2 from Thunderstore.

**Comment by RockerKitten** [comment]
That is correct, and there is no hot key. It is noted in the installation section of the mod description however that you'll need something like Comfy's Sears Catalogue to enable a larger and/or scrollable build menu.
